---
title: Model development
journal: "TBC"
author:
- name: 'Tom Ravalde\corref{cor1}'
  email: thomas.ravalde08@imperial.ac.uk
  group:
  address:
- name: James Keirstead
  email: j.keirstead@imperial.ac.uk
  group:
  address:
address-general: "Department of Civil and Environmental Engineering, Imperial College London"
biblio-files: "my-refs.bib"
topline: (Draft.)
options: "review, authoryear"
date: \VCDateISO
abstract:
  To be completed.

keywords: "to, be, completed"
---

```{r Setup, include=FALSE, results="hide", warning=FALSE}
opts_chunk$set(fig.path = "figures/", dev=c("cairo_pdf"), fig.pos='htbp', fig.width=5, fig.height=3.5, dpi=700, fig.show='hold', fig.lp="fig:", cache=FALSE, par=TRUE, echo=FALSE, results="hide", message=FALSE, warning=FALSE)

library(extrafont)
font_import(pattern="LinBiolinum")
```

# Introduction 

- Concerned with the model formulation and validation

# Benchmarking

- Benchmarking model of default probabilities of listed companies
  	- http://papers.ssrn.com/sol3/papers.cfm?abstract_id=982984
- Benchmarking default prediction models: pitfalls and remedies in model validation
	- http://www.rogermstein.com/wp-content/uploads/BenchmarkingDefaultPredictionModels_TR030124.pdf	

## "Benchmarking problems"

- Evolutionary computation benchmark problems
  	- http://www.cs.cmu.edu/afs/cs/project/jair/pub/volume24/ortizboyer05a-html/node6.html
- A generalized appraoch to construct benchmark problems for dynamic optimization:
  	- http://www.cs.le.ac.uk/people/sy11/Papers/SEAL08_3.pdf
- A benchmark study of optimization search algorithms
  	- http://www.redcedartech.com/pdfs/SHERPA_Benchmark_0110.pdf
- Collins definition:
  	- http://dictionary.reverso.net/english-cobuild/benchmark%20problem
- A library of problems:
  	- http://iftomm-multibody.org/benchmark/browse/ 
	- Example problems: flyball governor, uncontrolled bicycle, dynamic gait analysis, 
- PROBEN1 -- A set of neural network benchmark problems and benchmarking rules
- Popular benchmark problems for geometric nonlinear analysis of shells:
  	- http://www.sciencedirect.com/science/article/pii/S0168874X0300218X
- Some benchmark problems in electromagnetics
  	- http://www.numa.uni-linz.ac.at/Teaching/Bachelor/oberndorfer-bakk.pdf
	- "The purpose of a benchmark is to assess the relative performance of an object."
- Benchmark problems for incompressible fluid flows with structural interactions
  	- http://web.mit.edu/kjb/www/Principal_Publications/Benchmark_Problems_for_Incompressible_Fluid_Flows_with_Structural_Interactions.pdf
- BioPreDyn-bench: a suite of benchmark problems for dynamic modelling in systems biology
  	- http://www.ncbi.nlm.nih.gov/pubmed/25880925
- Robust control design for a benchmark problem
  	- http://deepblue.lib.umich.edu/bitstream/handle/2027.42/76996/aiaa-20949-475.pdf?sequence=1
- Benchmark problems from vehicle dynamics
  	- http://link.springer.com/article/10.1007/s12206-015-0504-4#page-1
- Discrete location problems: benchmark library
  	- http://www.math.nsc.ru/AP/benchmarks/english.html
	- E.g. simple plant location problem
- Benchmark structural control problem for seismically excited highway bridge
  	- http://www-ce.engr.ccny.cuny.edu/People/Agrawal/Highway%20Benchmark%20Problem.htm
- Two-objective design of benchmark problems of a water distribution system via MOEs: Towards the best-known approximation of the true pareto front
  	- http://ascelibrary.org/doi/abs/10.1061/(ASCE)WR.1943-5452.0000460
- Non-symmetric benchmark problem:
  	- http://ta.twi.tudelft.nl/nw/users/vuik/software/laplace/problem.pdf
  	- Navier-Stokes
- Energy storage benchmark problems
  	- http://castlelab.princeton.edu/Datasets/Time-dependent_storage/readme.pdf
- A comparison of approximate dynamic programming tecnhiques on benchmark energy: does anything work?
  	- http://castlelab.princeton.edu/Papers/Jiang-ComparisonADPonBenchmarkEnergy-DoesAnythingWorkJune52014.pdf
- Optimization benchmark problem for energy plant operational planning problem
  	- http://www.ssl.nd.chiba-u.jp/~okamoto/BP-IA/en/P1.html
- Waste collection vehicle routing problem with time windows:
  	- http://www.sciencedirect.com/science/article/pii/S0305054805001322
- Benchmark problems for repository siting models
  	- http://www.osti.gov/scitech/biblio/6614989
	- Nuclear waste storage
- An efficient variable neighborhood search heuristic for very large scale vehicle routing problems
  	- http://www.sciencedirect.com/science/article/pii/S0305054805003394
- A new evolutionary approach to cutting stock problems with and without contiguity
  	- http://www.sciencedirect.com/science/article/pii/S0305054801000399
- Nonnparametric input estimation in physiological systems: Problems, methods, and case studies
	- http://www.sciencedirect.com/science/article/pii/S0005109896002543
- A handbook of industrial ecology
  	- http://evirtual.uaslp.mx/Ambiental/PyGAmbiental/Biblioteca/Handbook_Industrial_Ecology_2002.pdf#page=135
	- 'Benzene production: a benchmark multi-objective example' (p.127)
- Industrial and ecological cumulative exergy consumption of the United States via the 1997 input-output benchmark model
- Competent genetic-evolutionary optimization of water distribution systems
  	- http://ascelibrary.org/doi/abs/10.1061/(ASCE)0887-3801(2001)15:2(89)
- The wrong paradigm: why water distribution optimization doesn't work
  	- http://ascelibrary.org/doi/abs/10.1061/(ASCE)0733-9496(2001)127:4(203)
- A modified shuffled from-leaping optimization algorithm: applications to project management
  	- http://www.tandfonline.com/doi/full/10.1080/15732470500254535#abstract
- Evolutionary multi-objective optimization of the design and operation of water distribution network: total cost vs. reliability vs. water quality
	- http://www.iwaponline.com/jh/008/jh0080165.htm
- Optimization of water distribution network design using differential evolution
- Benchmark problems for design and optimisation of water distribution systems
  	- https://books.google.com/books?hl=en&lr=&id=SCUT4QDVkJEC&oi=fnd&pg=PA249&dq=benchmark+problems+AND+water+management&ots=gGB3EhNLBD&sig=qV-J7mZdEturBGoZE9lJCVkrF2U#v=onepage&q=benchmark%20problems%20AND%20water%20management&f=false
# Acknowledgements {.unnumbered}

Tom Ravalde is supported by the EPSRC Doctoral Training Partnership at Imperial College London.
